apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
        - image: pokapi:0.1
          name: pokedex
          ports:
            - containerPort: 3000
          env:
            - name: POKEDEX_NAME
              valueFrom:
                configMapKeyRef:
                  name: pokedex-cm
                  key: POKEDEX_NAME